using flatcc

exe{basics}: cxx{basics} fbs.c{t}
fbs.c{t}: fbs{t}

fbs.c{t}: flatcc.options =+ --common_builder --common_reader --builder
c.poptions =+ "-I$out_root/basics" "-I$src_root/basics"
cxx.poptions =+ "-I$out_root/basics" "-I$src_root/basics"
c.libs += -lflatccrt
cxx.libs += -lflatccrt
